POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "mafe",
  "email": "mafe@gmail.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "clientId": "fc619037-4c8f-42bb-ac60-96b3c2b9140e"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "accountIDFrom": "fab64237-6e11-4152-80ac-2cdd8a5a86dd",
  "accountIDTo": "e67b0ed1-7b13-45d7-ad20-1c9682842635",
  "amount": 1
}
