POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "mafe",
  "email": "mafe@gmail.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "clientId": "468d90a6-0d07-48e9-939a-7d5cb0f225de"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "accountIDFrom": "94a18c82-3767-429f-9dd2-d9995eb08129",
  "accountIDTo": "bc3319ad-dd18-4c2a-93a8-3ba0ff80504a",
  "amount": 50
}
